services:
  app:
    image: ghcr.io/kimdre/doco-cd:0.110.1
    hostname: doco-cd
    networks:
      - external_proxy_network
      - apprise_network
    environment:
      LOG_LEVEL: debug
      TZ: Europe/Vienna
      GIT_ACCESS_TOKEN_FILE: /run/secrets/git_access_token
      # fallback polling configuration, in case webhooks are missed
      POLL_CONFIG: |
        - url: https://github.com/xfallme/homelab-swarm.git
          reference: main
          interval: 24h
      SECRET_PROVIDER: 1password
      SECRET_PROVIDER_ACCESS_TOKEN_FILE: /run/secrets/1password_service_account_token
      WEBHOOK_SECRET_FILE: /run/secrets/webhook_secret
      APPRISE_API_URL: http://apprise:8000/notify
      APPRISE_NOTIFY_LEVEL: success
      APPRISE_NOTIFY_URLS_FILE: /run/secrets/apprise_notify_urls
    secrets:
      - git_access_token
      - 1password_service_account_token
      - webhook_secret
      - apprise_notify_urls
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/swarm-data/doco-cd/data:/data
    healthcheck:
      test: [ "CMD", "/doco-cd", "healthcheck" ]
      start_period: 120s # higher because of 1password
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  external_proxy_network:
    external: true
  apprise_network:
    external: true

secrets:
  git_access_token:
    external: true
  1password_service_account_token:
    external: true
  webhook_secret:
    external: true
  apprise_notify_urls:
    external: true