services:
  app:
    container_name: doco-cd-updater
    image: ghcr.io/kimdre/doco-cd:0.109.2
    environment:
      TZ: Europe/Vienna
      HTTP_PORT: 8000
      GIT_ACCESS_TOKEN_FILE: /run/secrets/git_access_token
      POLL_CONFIG: |
        - url: https://github.com/xfallme/homelab-swarm.git
          reference: main
          interval: 15m
          target: updater # deploys the updater target on change
      SCHEDULER_ENABLED: 'false' # disable scheduler on updater instance
    secrets:
      - git_access_token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/swarm-data/doco-cd/updater-data:/data

secrets:
  git_access_token:
    external: true