name: test
destroy: false
working_dir: /deploy/test
compose_files: 
  - test.compose.yaml
external_secrets:
  INTERNAL_DOMAIN: "op://GitOps/Data/internal_domain"
  EXTERNAL_DOMAIN: "op://GitOps/Data/external_domain"
---
name: reverse_proxy
working_dir: /deploy/reverse_proxy
build_opts:
  force_image_pull: true
compose_files:
  - reverse_proxy.compose.yaml
external_secrets:
  EMAIL: "op://GitOps/Data/email"
  CROWDSEC_API_KEY: "op://GitOps/CADDY_CROWDSEC_API_KEY/credential"
  INTERNAL_DOMAIN: "op://GitOps/Data/internal_domain"
  EXTERNAL_DOMAIN: "op://GitOps/Data/external_domain"
  CLOUDFLARE_API_TOKEN: "op://GitOps/CADDY_CLOUDFLARE_API_TOKEN/credential"