name: test
destroy: true
working_dir: /deploy/test
compose_files: 
  - test.compose.yaml
---
name: reverse_proxy
working_dir: /deploy/reverse_proxy
build_opts:
  no_cache: false
compose_files:
  - reverse_proxy.compose.yaml