services:
  core:
    image: ghcr.io/home-assistant/home-assistant:2026.9.1
    networks:
      - proxy_network
      - internal
    user: 1000:1000
    environment:
      TZ: Europe/Vienna
    volumes:
      - /mnt/swarm-data/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      labels:
        caddy: https://ha.$EXTERNAL_DOMAIN
        caddy.reverse_proxy: "{{upstreams 8123}}"

  z2m:
    image: ghcr.io/koenkk/zigbee2mqtt:2.13.0
    networks:
      - proxy_network
      - internal
    user: 1000:1000
    environment:
      TZ: Europe/Vienna
    volumes:
      - /mnt/swarm-data/homeassistant/zigbee2mqtt:/app/data
    deploy:
      replicas: 1
      labels:
        caddy: z2m.$EXTERNAL_DOMAIN
        caddy.reverse_proxy: "{{upstreams 8080}}"
        caddy.import: tinyauth_forwarder *

  mosquitto:
    image: eclipse-mosquitto:2.1.2-alpine
    networks:
      - internal
    user: 1000:1000
    environment:
      TZ: Europe/Vienna
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mnt/swarm-data/homeassistant/mosquitto/data:/mosquitto/data
      - /mnt/swarm-data/homeassistant/mosquitto/log:/mosquitto/log
    deploy:
      replicas: 1

networks:
  proxy_network:
    external: true
  internal:
    driver: overlay
